#@+leo-ver=5-thin
#@+node:swot.20250907092048.1: * @file src/main/resources/application.yml
#@@language yaml
#@+others
#@+node:swot.20250907092048.3: ** spring 新增配置 redis
#@+doc
# [source,python]
# ----
#@@c
#@@language python
spring:
    application:
        name: mybatis_quickstart-crud
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/general_manager
        username: root
        password: root
    servlet:
        multipart:                  # 上传文件
            max-file-size: 10MB     # 指定单个文件上传的大小
            max-request-size: 100MB  # 指定单次请求上传文件的总大小

    # --- New Added 配置 redis ---
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        # password: 未设置，默认安装的 redis 没有密码
#@+doc
# ----
#
#@+node:swot.20250907092048.2: ** @ignore-tree 
#@+others
#@+node:swot.20250907092048.4: *3* mybatis
mybatis:
    configuration:
        # 指定mybatis输出日志的位置, 输出控制台
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        #开启驼峰命名自动映射，即从经典数据库列名 a_column 映射到经典 Java 属性 名 aColumn
        map-underscore-to-camel-case: true
#@+node:swot.20250907092048.5: *3* 阿里云 OSS
# 与之对应引用为 @Vaule("${aliyun.oss.endpoint}")
# noinspection undefined
aliyun:
    oss:
        endpoint: "https://oss-cn-beijing.aliyuncs.com"
        accessKeyId: "[REMOVED]"
        accessKeySecret: "[REMOVED]"
        bucketName: "swot-learn"
#@+node:swot.20250907092048.6: *3* 开启事务日志 logging
#@+doc
# [source,yaml]
# ----
#@@c
#@@language yaml
logging:
    level:
        # noinspection undefined
        org.springframework.jdbc.support.JdbcTransactionManager: debug
#@+doc
# ----
#@-others
#@-others
#@-leo
