:source-highlighter: pygments
:icons: font
:scripts: cjk
:stem: latexmath
:toc:
:toc: right
:toc-title: 目录
:toclevels: 3
:tip-caption: ⚡
:note-caption: ❕
:important-caption: ❗
:warning-caption: ‼️
:caution-caption: ⚠️

= 2026-01-25 从 podman postgresql17 迁移数据到 windows 绿色包环境

++++
<button id="toggleButton">目录开关</button>
<script>
    // 获取按钮和 div 元素
    const toggleButton = document.getElementById('toggleButton');
    const contentDiv = document.getElementById('toc');
    contentDiv.style.display = 'block';

    // 添加点击事件监听器
    toggleButton.addEventListener('click', () => {
        // 切换 div 的显示状态
        // if (contentDiv.style.display === 'none' || contentDiv.style.display === '') {
        if (contentDiv.style.display === 'none') {
            contentDiv.style.display = 'block';
        } else {
            contentDiv.style.display = 'none';
        }
    });
</script>
++++

== 从 Macos 导出数据
从 podman 中导出 postgresql 数据

1. 在容器内生成文件（直接由 pg_dump 写入磁盘，不经过终端管道）
+
[source,console]
----
podman exec pg17-server pg_dump -U postgres -n data_management -Fc data_management -f /tmp/safe_data.dump
----

2. 将文件从容器内部拷贝出来
+
[source,console]
----
podman cp pg17-server:/tmp/safe_data.dump ./data_management.dump
----

3. 验证文件完整性（必须显示为: PostgreSQL custom dump archive）
[source,console]
----
> file ./data_management.dump
data_management.dump: PostgreSQL custom database dump - v1.16-0
----

== 从 windows 导入数据
. 解压 postgresql-17.7-2-windows-x64-binaries.zip

. 进入 bin 目录
+
[source,console]
----
cd E:\deploy\postgresql-17.7-2-windows-x64-binaries\pgsql\bin
---- 

. 初始化数据库：
+
.C:\pgsql\data 是数据库文件保存目录
[source,console]
----
.\initdb.exe -D C:\pgsql\data -U postgres -W -E UTF8
----

. 启动数据库服务：
+
[source,console]
----
.\pg_ctl.exe -D C:\pgsql\data -l logfile start
----

. 创建数据库：
+
.先指定初始化时自动创建的数据库 postgres 来进行连接，要不然创建不了数据库 data_management。
[source,console]
----
.\psql.exe -U postgres -d postgres -c "CREATE DATABASE data_management;"
----

. 将导出的数据复制到 windows
+
.导入数据
[source,console]
----
.\pg_restore.exe -U postgres -d data_management -v --no-owner "../../../data_management.dump"
----

