:source-highlighter: pygments
:icons: font
:scripts: cjk
:stem: latexmath
:toc:
:toc: right
:toc-title: 目录
:toclevels: 3
:tip-caption: ⚡
:note-caption: ❕
:important-caption: ❗
:warning-caption: ‼️
:caution-caption: ⚠️

= windows_制作绿色版_nodejs24_postgresql17_绿色动力沙盘数据管理系统

++++
<button id="toggleButton">目录开关</button>
<script>
    // 获取按钮和 div 元素
    const toggleButton = document.getElementById('toggleButton');
    const contentDiv = document.getElementById('toc');
    contentDiv.style.display = 'block';

    // 添加点击事件监听器
    toggleButton.addEventListener('click', () => {
        // 切换 div 的显示状态
        // if (contentDiv.style.display === 'none' || contentDiv.style.display === '') {
        if (contentDiv.style.display === 'none') {
            contentDiv.style.display = 'block';
        } else {
            contentDiv.style.display = 'none';
        }
    });
</script>
++++

== 2026-01-22 mysql:8 迁移到 postgresql:17


=== step1: export data from mysql:8 to mysql:5.7
. 导出 mysql8 中的数据
* mysqldump -h your_mysql_server_ip -u root -p database_name > export_file_name.sql


. 转换排序编码（mysql5.7 不认 mysql8 的排序）
* sed 's/utf8mb4_0900_ai_ci/utf8mb4_general_ci/g' export_file_name.sql > export_file_name_fixed.sql
* 要使用 mysql5.7 是因为 mysql8 不支持 pgloader


. 启动一个旧版本的 MySQL，它天然支持 #pgloader# 的所有协议（会自动去 pull 镜像）
+
[source,console]
----
podman run --name mysql-bridge \
  -e MYSQL_ROOT_PASSWORD=mypass \
  -p 3307:3306 \
  -d docker.m.daocloud.io/library/mysql:5.7
----


. 等几秒钟容器启动后，创建 database 并导入数据
+
[source,console]
----
mysql -h 127.0.0.1 -P 3307 -u root -pmypass -e "CREATE DATABASE database_name;"
mysql -h 127.0.0.1 -P 3307 -u root -pmypass data_management < export_file_name_fixed.sql
----

=== step2: prepare database postgresql:17
. 下载 postgresql 17 image
+
[source,console]
----
podman pull docker.m.daocloud.io/library/postgres:17
----


. 查看 image
+
[source,console]
----
> podman image list
REPOSITORY                             TAG         IMAGE ID      CREATED      SIZE
docker.m.daocloud.io/library/postgres  17          1268669160cb  9 days ago   461 MB
docker.m.daocloud.io/library/node      22-slim     f9834cd4819c  3 weeks ago  232 MB
----


. 运行 postgresql 容器（数据库密码是 naonao）
+
[source,console]
----
podman run --name pg17-server \
  -e POSTGRES_PASSWORD=naonao \
  -p 5432:5432 \
  -v pgdata_vol:/var/lib/postgresql/data:Z \
  -d docker.m.daocloud.io/library/postgres:17
----
+
[TIP]
====
[loweralpha]
1. 如果想确认这个 pgdata_vol 到底在宿主机的哪个物理位置，可以运行： +
podman volume inspect pgdata_vol

2. pgdata_vol 是自己起的卷名，查看目前电脑上已经有哪些命名卷了，可以运行： +
podman volume ls

3. :Z	SELinux 选项	授权证明，允许读写（在 windows10/11 或者 macos 上可以不加 Z 选项）
====


. 查看容器已经在运行了
+
[source,console]
----
> podman container list
CONTAINER ID  IMAGE                                     COMMAND     CREATED        STATUS        PORTS                   NAMES
eb26e62fd368  docker.m.daocloud.io/library/postgres:17  postgres    7 seconds ago  Up 7 seconds  0.0.0.0:5432->5432/tcp  pg17-server
----

. 创建数据库 data_management
+
[source,console]
----
podman exec -it pg17-server psql -U postgres -c "CREATE DATABASE data_management;"
----

=== step3: import data from mysql:5.7 to postgresql:17
. 创建文件 migrate.load
+
[source,console]
----
LOAD DATABASE
     FROM mysql://root:mypass@127.0.0.1:3307/data_management
     INTO postgresql://postgres:naonao@localhost:5432/data_management

 WITH include drop, create tables, create indexes, reset sequences, foreign keys

  SET maintenance_work_mem to '128MB', 
      work_mem to '12MB'

 CAST 
      -- 1. 强制将所有 tinyint(x) 转换为 boolean，并丢弃修饰符
      type tinyint to boolean drop typemod using tinyint-to-boolean,
      
      -- 2. 针对这种已经变成了 boolean(4) 的情况，显式拦截 boolean 类型并丢弃修饰符
      type boolean to boolean drop typemod,
      
      -- 3. 时间类型转换
      type datetime to timestamptz drop default;
----


. 运行 pgloader 容器执行迁移
+
.在终端中切换到 migrate.load 所在的目录，运行以下命令
[source,console]
----
pgloader migrate.load
----
+
TIP: 在 macos 中安装 pgloader：`brew install pgloader`

. 查看 postgresql 中的数据是否正确

== 2026-01-25 从 podman postgresql17 迁移数据到 windows 绿色包环境


=== step1: 从 Macos 导出数据
从 podman 中导出 postgresql 数据

1. 在容器内生成文件（直接由 pg_dump 写入磁盘，不经过终端管道）
+
[source,console]
----
podman exec pg17-server pg_dump -U postgres -n data_management -Fc data_management -f /tmp/safe_data.dump
----

2. 将文件从容器内部拷贝出来
+
[source,console]
----
podman cp pg17-server:/tmp/safe_data.dump ./data_management.dump
----

3. 验证文件完整性（必须显示为: PostgreSQL custom dump archive）
[source,console]
----
> file ./data_management.dump
data_management.dump: PostgreSQL custom database dump - v1.16-0
----

=== step2: 从 windows 导入数据
. 解压 postgresql-17.7-2-windows-x64-binaries.zip

. 进入 bin 目录
+
[source,console]
----
cd E:\deploy\postgresql-17.7-2-windows-x64-binaries\pgsql\bin
---- 

. 初始化数据库：
+
.C:\pgsql\data 是数据库文件保存目录
[source,console]
----
.\initdb.exe -D C:\pgsql\data -U postgres -W -E UTF8
----

. 启动数据库服务：
+
[source,console]
----
.\pg_ctl.exe -D C:\pgsql\data -l logfile start
----

. 创建数据库：
+
.先指定初始化时自动创建的数据库 postgres 来进行连接，要不然创建不了数据库 data_management。
[source,console]
----
.\psql.exe -U postgres -d postgres -c "CREATE DATABASE data_management;"
----

. 将导出的数据复制到 windows
+
.导入数据
[source,console]
----
.\pg_restore.exe -U postgres -d data_management -v --no-owner "../../../data_management.dump"
----

== 2026-01-29 在 windows 下生成项目 node_modules 目录
. 解压: node-v24.13.0-win-x64.zip

. 移动文件夹：
    * 建议将解压后的 node-v24.13.0-win-x64 文件夹移到一个固定的位置，例如 C:\Program Files\nodejs。

. 设置系统 Path：
    .. 按下 Win + S 搜索 “编辑系统环境变量” 并打开。
    .. 点击 “环境变量” 按钮。
    .. 在“系统变量”栏找到 Path，点击“编辑”。
    .. 点击“新建”，将你刚才 Node.js 文件夹的全路径粘贴进去（例如 C:\Program Files\nodejs）。
    .. 一路点击“确定”保存

. 复制项目 sandbox 到 windows 系统中，然后安装依赖
+
[source,console]
----
cd sandbox/backend
npm install
----

