:source-highlighter: pygments
:icons: font
:scripts: cjk
:toc:
:toc: right
:toc-title: Table of Contents
:toclevels: 3

= learning contents

++++
<button id="toggleButton">Table of Contents</button>
<script>
    // 获取按钮和 div 元素
    const toggleButton = document.getElementById('toggleButton');
    const contentDiv = document.getElementById('toc');
    contentDiv.style.display = 'none';

    // 添加点击事件监听器
    toggleButton.addEventListener('click', () => {
        // 切换 div 的显示状态
        // if (contentDiv.style.display === 'none' || contentDiv.style.display === '') {
        if (contentDiv.style.display === 'none') {
            contentDiv.style.display = 'block';
        } else {
            contentDiv.style.display = 'none';
        }
    });
</script>
++++

== Read document
The AsciiDoc file(.adoc) is intended for online viewing, while the HTML file(.html) is for offline access.

== Learning Structure
. Use leo-editor's swot-learning.leo file to manage outlined knowledge.

. swot-learning.leo is managed by git.

. .gitignore add each project.

. Each project is managed by it's own git.

. Each project use pnpm-workspace.yaml of monorepo.

. Use `git worktree` to manage each project.

== Asciidoctor
Asciidoctor is a fast, open source, text processor for parsing AsciiDoc into a document model, then converting it to output formats such as HTML 5, DocBook 5, man(ual) pages, PDF, and EPUB 3. Asciidoctor is written in the Ruby programming language.

xref:asciidoctor/asciidoctor.adoc[ Read Asciidoctor learning Notes ]

https://docs.asciidoctor.org/asciidoctor/latest/[ Asciidoctor Documentation ]

== Git
Git is a free and open source distributed version control system designed to handle everything from small to very large projects with speed and efficiency.

xref:git/git.adoc[ Read git learning Notes ]

https://git-scm.com/

https://git-scm.com/downloads

== LEO-Editor
Leo is a PIM, IDE and outliner that accelerates the work flow of programmers, authors and web designers. 
Outline nodes may appear in more than one place, allowing multiple organizations of data within a single outline.

xref:leo-editor/leo-editor.adoc[ Read leo-editor learning Notes ]

https://leo-editor.github.io/leo-editor/[ Leo’s Home Page ]

https://github.com/leo-editor/leo-editor[ Leo's GitHub repository ]

https://groups.google.com/g/leo-editor[ Leo's forum ]

== Nuxt3
The Progressive Web Framework

xref:nuxt/nuxt3/nuxt3.adoc[ Read Nuxt3 learning Notes ]

https://nuxt.com/

https://github.com/nuxt/nuxt

== Redis
https://github.com/redis/redis

For developers, who are building real-time data-driven applications, Redis is the preferred, fastest, and most feature-rich cache, data structure server, and document and vector query engine.

== Software-Designer
Now only for Chinese.

xref:software-designer/software-designer.adoc[ Read software-designer learning Notes ]

https://bm.ruankao.org.cn/sign/welcome

https://ruankaodaren.com/exam/#/

== 五笔86 -> 70后的最爱
https://github.com/wangzhaohe/swot-learning/blob/main/wubi86/wubi86.adoc

