#@+leo-ver=5-thin
#@+node:swot.20251012184017.1: * @file gateway/src/main/resources/application-route.yml
#@@language yaml
#@+others
#@+node:swot.20251012184252.1: ** spring
#@+doc
# [source,scss]
# ....
#@@c
#@@language xml
spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://app-order
          predicates:
            - Path=/api/order/**
        - id: item-route
          uri: lb://app-item
          predicates:
            - Path=/api/item/**
#@+doc
# ....
#@-others
#@-leo
