#@+leo-ver=5-thin
#@+node:swot.20251012223319.1: * @file gateway/src/main/resources/application-route.yml
#@@language yaml
#@+others
#@+node:swot.20251012223319.2: ** spring
#@+doc
# [source,yaml]
# ....
#@@c
#@@language yaml
spring:
  cloud:
    gateway:
      routes:
        - id: order-route
          uri: lb://app-order
          predicates:
            - Path=/api/order/**
        - id: item-route
          uri: lb://app-item
          predicates:
            - Path=/api/item/**
        # 兜底路由
        - id: bing-route
          uri: https://cn.bing.com/
          predicates:
            - Path=/**
#@+doc
# ....
#@-others
#@-leo
