:source-highlighter: pygments
:icons: font
:scripts: cjk
:toc:
:toc: right
:toc-title: Table of Contents
:toclevels: 3

= Learning Leo

++++
<button id="toggleButton">Table of Contents</button>
<script>
    // 获取按钮和 div 元素
    const toggleButton = document.getElementById('toggleButton');
    const contentDiv = document.getElementById('toc');
    contentDiv.style.display = 'none';

    // 添加点击事件监听器
    toggleButton.addEventListener('click', () => {
        // 切换 div 的显示状态
        // if (contentDiv.style.display === 'none' || contentDiv.style.display === '') {
        if (contentDiv.style.display === 'none') {
            contentDiv.style.display = 'block';
        } else {
            contentDiv.style.display = 'none';
        }
    });
</script>
++++

== Install leo-editor from source
1. Clone leo-editor source code

    git clone https://github.com/leo-editor/leo-editor.git

2. Install python3

    https://www.python.org/downloads/

3. Create a Python virtual environment

    python3 -m venv your_environment_name
    source your_environment_name/bin/activate

4. Install some packages
+
....
pip install pyqt6
pip install PyQtWebEngine
pip install docutils markdown nbformat numpy matplotlib nbconvert pygments
pip install jupyter-client==6.1.12 qtconsole // <1>
....
+
<1> for python debug in shell
NOTE: jupyter-client-7.3.4 has bug, and can't run `qtconsole`
+
.Change pip source
[NOTE]
====
pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
====

5. launch leo-editor

    python launchLeo.py

== Config leo-editor


=== 复制 leo 自定义配置文件
[source,console]
----
cp .leo/myLeoSettings.leo ~/.leo/
----

=== 复制 leo 主题文件
[source,console]
----
cp .leo/themes/SwotMoknokai.leo ~/.leo/themes/
----

== Nav Search
Leo Editor 的 Nav（“Nav” 标签页）搜索功能是支持正则表达式的，不过需要借助 leo's QuickSearch 插件，你需要确保已加载此插件。

以下是详情：

1. 确保在 Leo > Plugins 配置中已启用 quicksearch.py 插件。

2. 切换到 Nav 标签页（通常在 Log 窗口）。

3. 输入搜索内容：

* 普通搜索：例如 todo* 使用通配符；
* 正则搜索：例如 r:^def\s+\w+ 查找以 def 开头的函数定义；
* 不区分大小写：使用 r:(?i)pattern。

回车执行搜索

== Teaching by leo-editor


=== write code
When writing code, it is often necessary to add a lot of explanatory text. The commonly adopted approach is to directly write single-line comments or a large number of block comments in the code.

If these comments in the code could be formatted like an article, the effect would be much better.


在编写代码时，往往需要加入很多说明文字，经常采用的方式是直接在代码里写单行注释或者大量块注释。

如果代码里的这些注释能够有像文章一样的排版体现，效果就会好很多。

=== write document
Teaching documents are typically presented in the form of PowerPoint (PPT) files. However, PPTs are generally used for summarizing and presenting information during live sessions and should be complemented by detailed Word or Markdown files to serve as practical operational aids. 

In programming-related teaching materials, the primary source code of demonstration programs is usually included. Typically, the relevant portions of the source code are copied into the documentation. This practice introduces the challenge of ensuring that the documentation is promptly updated whenever changes are made to the source code.

Therefore, if a method could be devised to write the source code concurrently with the documentation, a significant amount of repetitive labor and time could be saved.


教学文档通常为 ppt 文件，但是 ppt 一般做为临场提纲挈领的演示，需要再配合详尽的 word 或者 markdown 文件来作为实操辅助。

在编程的教学文档里，会包含演示程序的主要源代码。通常会把需要的部分源代码复制到文档里。这样就存在源代码更改后需要再及时更改文档的问题。

所以如果能够在编写文档的同时编写源代码，将会节省大量重复劳动的时间。

== 基于 x86 的库如何在 macos arm 架构下运行
如果在 arm64 的 MacOS 下不能运行 leo-editor，可以试试下面的方法。

怎么样在 M1|M2 Mac终端中快速切换 arm64 或 x86 架构
https://aibi8.com/news/3140.html

在 M1|M2|M3 Mac上，可以使用 arch 命令在终端中快速切换架构。

要从 ARM64 切换到 x86 架构，请在终端中输入以下命令：

    arch -x86_64 zsh

此命令将在当前终端会话中切换到 x86_64 架构，以便可以在 M1|M2|M3 MacOS 上运行只适用于 x86 架构的应用程序。

要从 x86 切换回 ARM64 架构，请在终端中输入以下命令：

    arch -arm64 zsh

这将在当前终端会话中切换回 ARM64 架构。请注意，只有 M1|M2|M# MacOS 支持 ARM64 架构。

== 列操作模式 rectangle
The following is from LeoDocs.leo. Selecting some text with mouse or keyboard arrow key, then between the first cursor and the end cursor is the columns that being selected.

------

.. _`Emacs rectangle commands`: http://www.gnu.org/software/emacs/manual/html_node/emacs/Rectangles.html

The following commands emulate the `Emacs rectangle commands`_::

```
rectangle-clear
rectangle-delete

rectangle-open
rectangle-close

rectangle-kill
rectangle-yank

rectangle-string
```

Given::

```
I'm really glad the docs are being updated. I know that's a
monumental task. I only use a fraction of Leo's commands, mostly
because I don't even know what they're supposed to accomplish. A few
examples:
```

Placing the cursor immediately before the first "I", holding shift and moving it to immediately before the word`examples` selects a zero width rectangle from the beginning to the end of the selection (zero width because the selection starts and ends in the same column. Then running `rectangle-string [largo]<space><enter>` yields::

....
[largo] I'm really glad the docs are being updated. I know that's a
[largo] monumental task. I only use a fraction of Leo's commands, mostly
[largo] because I don't even know what they're supposed to accomplish. A few
[largo] examples:
....

