:source-highlighter: pygments
:icons: font
:scripts: cjk
:stem: latexmath
:toc:
:toc: right
:toc-title: Table of Contents
:toclevels: 4

= Nuxt Notes

++++
<button id="toggleButton">Table of Contents</button>
<script>
    // 获取按钮和 div 元素
    const toggleButton = document.getElementById('toggleButton');
    const contentDiv = document.getElementById('toc');
    contentDiv.style.display = 'block';

    // 添加点击事件监听器
    toggleButton.addEventListener('click', () => {
        // 切换 div 的显示状态
        // if (contentDiv.style.display === 'none' || contentDiv.style.display === '') {
        if (contentDiv.style.display === 'none') {
            contentDiv.style.display = 'block';
        } else {
            contentDiv.style.display = 'none';
        }
    });
</script>
++++

== @path nuxt3-basic


=== github link
https://github.com/wangzhaohe/nuxt3-basic.git

=== Create a new project
https://nuxt.com/docs/getting-started/installation#new-project

Prepare Directory

    mkdir -p nuxt/nuxt3

IMPORTANT: nuxt3-basic 作为最基本的项目目录，后面会使用 `git worktree` 把不同分支的目录放在 nuxt3目录下，它们和 nuxt3-basic 在同级目录下。这样后面再有 nuxt4 的项目，也可以放在 nuxt 目录下，和 nuxt3 目录平行放置。


Create a new nuxt3 project

    cd nuxt/nuxt3
    pnpm create nuxt nuxt3-basic


.Install some recommended library
....
> pnpm create nuxt nuxt3-basic

        .d$b.
       i$$A$$L  .d$b
     .$$F` `$$L.$$A$$.
    j$$'    `4$$:` `$$.
   j$$'     .4$:    `$$.
  j$$`     .$$:      `4$L
 :$$:____.d$$:  _____.:$$:
 `4$$$$$$$$P` .i$$$$$$$$P`

ℹ Welcome to Nuxt!                                                                                                                                nuxi 11:13:07 AM
ℹ Creating a new project in nuxt3-basic.                                                                                                          nuxi 11:13:07 AM

✔ Which package manager would you like to use?
pnpm
◐ Installing dependencies...                                                                                                                       nuxi 11:13:09 AM
 WARN  9 deprecated subdependencies found: @types/parse-path@7.1.0, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, inflight@1.0.6, node-domexception@1.0.0, npmlog@5.0.1, rimraf@3.0.2
Packages: +763

Progress: resolved 836, reused 757, downloaded 11, added 763, done

> nuxt-app@ postinstall /Users/swot/swot-learning/nuxt/nuxt3/nuxt3-basic
> nuxt prepare

✔ Types generated in .nuxt                                                                                                                        nuxi 11:13:21 AM

dependencies:
+ nuxt 3.17.4
+ vue 3.5.14
+ vue-router 4.5.1

Done in 11.6s
✔ Installation completed.                                                                                                                         nuxi 11:13:21 AM

✔ Initialize git repository?
Yes
ℹ Initializing git repository...                                                                                                                  nuxi 11:13:25 AM

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/swot/swot-learning/nuxt/nuxt3/nuxt3-basic/.git/

✔ Would you like to install any of the official modules?
@nuxt/eslint – Project-aware, easy-to-use, extensible and future-proof ESLint integration, @nuxt/fonts – Add custom web fonts with performance in mind, @nuxt/icon –
Icon module for Nuxt with 200,000+ ready to use icons from Iconify, @nuxt/image – Add images with progressive processing, lazy-loading, resizing and providers
support, @nuxt/scripts – Add 3rd-party scripts without sacrificing performance, @nuxt/ui – The Intuitive UI Library powered by Reka UI and Tailwind CSS
ℹ Resolved @nuxt/icon, @nuxt/image, @nuxt/scripts, @nuxt/ui, @nuxt/fonts, @nuxt/eslint, adding modules...                                         nuxi 11:16:40 AM
ℹ Installing @nuxt/icon@1.13.0, @nuxt/image@1.10.0, @nuxt/scripts@0.11.7, @nuxt/ui@3.1.2, @nuxt/fonts@0.11.4, @nuxt/eslint@1.4.1 as dependencies  nuxi 11:16:40 AM
 WARN  9 deprecated subdependencies found: @types/parse-path@7.1.0, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, inflight@1.0.6, node-domexception@1.0.0, npmlog@5.0.1, rimraf@3.0.2
Packages: +271
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1129, reused 1022, downloaded 3, added 271, done

dependencies:
+ @nuxt/eslint 1.4.1
+ @nuxt/fonts 0.11.4
+ @nuxt/icon 1.13.0
+ @nuxt/image 1.10.0
+ @nuxt/scripts 0.11.7
+ @nuxt/ui 3.1.2

Done in 19.8s
 WARN  9 deprecated subdependencies found: @types/parse-path@7.1.0, are-we-there-yet@2.0.0, gauge@3.0.2, glob@7.2.3, glob@8.1.0, inflight@1.0.6, node-domexception@1.0.0, npmlog@5.0.1, rimraf@3.0.2
Already up to date
Progress: resolved 1129, reused 1025, downloaded 0, added 0, done

dependencies:
+ @unhead/vue ^2.0.3
+ eslint ^9.0.0
+ typescript ^5.6.3

Done in 3s
ℹ Adding @nuxt/icon to the modules                                                                                                                nuxi 11:17:03 AM
ℹ Adding @nuxt/image to the modules                                                                                                               nuxi 11:17:03 AM
ℹ Adding @nuxt/scripts to the modules                                                                                                             nuxi 11:17:03 AM
ℹ Adding @nuxt/ui to the modules                                                                                                                  nuxi 11:17:03 AM
ℹ Adding @nuxt/fonts to the modules                                                                                                               nuxi 11:17:03 AM
ℹ Adding @nuxt/eslint to the modules                                                                                                              nuxi 11:17:03 AM
✔ ESLint config file created at /Users/swot/swot-learning/nuxt/nuxt3/nuxt3-basic/eslint.config.mjs                                                     11:17:05 AM
ℹ If you have .eslintrc or .eslintignore files, you might want to migrate them to the new config file                                                  11:17:05 AM
ℹ Nuxt Icon server bundle mode is set to local                                                                                                         11:17:05 AM
✔ Types generated in nuxt3-basic/.nuxt                                                                                                            nuxi 11:17:08 AM
                                                                                                                                                   nuxi 11:17:08 AM
✨ Nuxt project has been created with the v3 template. Next steps:
 › cd nuxt3-basic                                                                                                                                  nuxi 11:17:08 AM
 › Start development server with pnpm run dev
....

=== Setting nuxt.config.ts


==== @file nuxt.config.ts
[source,javascript,]
----
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
    compatibilityDate: '2025-05-15',
    devtools: { enabled: true },

    modules: [
        '@nuxt/icon',
        '@nuxt/image',
        '@nuxt/scripts',
        '@nuxt/ui',
        '@nuxt/fonts',
        '@nuxt/eslint'
    ],
    @others
});
----

===== 1 关闭默认的 google 访问设置
[source,javascript,]
----
/* 因为默认会使用 google 的字体和图标，
   但是 node.js 不会走代理，可能访问不到 google 网站
*/

// @nuxt/fonts 不使用 google fonts
fonts: {
    provider: 'none', // 禁用默认字体提供商（如 Google Fonts）
},

// Nuxt UI 就不会再尝试加载 Google Fonts
ui: {
    fonts: false
},
----

