#@+leo-ver=5-thin
#@+node:swot.20250521214125.1: * @file pnpm-workspace.yaml
#@+doc
# [source,yaml]
# ----
#@@c
#@@language yaml
packages:
  - 'nuxt3-basic'
  - 'nuxt3-element-plus'
  - 'nuxt3-layout'
  - 'nuxt3-tailwindcss'
  - 'nuxt3-font'
  - 'nuxt3-component'
  - 'nuxt3-sitemap'
  - 'nuxt3-sqlite'
  - 'nuxt3-slug'
  - 'nuxt3-server'

#@+doc
# ----
#@-leo
