#@+leo-ver=5-thin
#@+node:swot.20251024165757.1: * @file config-server/src/main/resources/config-repo/app-order-dev.yml
#@@language yaml
#@+others
#@+node:swot.20251024170506.1: ** @ignore-node config
#@+doc
# service-order 开发环境配置文件，当服务以 dev 环境启动时，app-order-dev.yml 会覆盖 app-order.yml 中相同配置项。
#
# [source,yaml]
# ----
#@@c
#@@language yaml
server:
  port: 8092

spring:
  application:
    name: app-order
  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: dev_user
    password: dev123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

# 应用业务配置 - 开发环境
app:
  name: 订单服务 (开发环境)
  version: 1.1.0-dev
  description: 这是一个订单微服务示例 - 开发环境，包含新功能测试"
  features:
    - 订单创建
    - 订单查询
    - 订单状态更新
    - 调试模式
    - 新功能测试
  limits:
    max-order-items: 3
    timeout-seconds: 120

# 演示配置 - 开发环境
demo:
  enabled: true
  message: "开发环境：正在测试新功能，请谨慎使用！"
  retry-count: 10
  cache-enabled: false
  debug-mode: true
  branch: dev

# 开发环境特定配置
logging:
  level:
    com.tjise.serviceorder: TRACE
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
#@+doc
# ----
#@+node:swot.20251024170555.1: ** resilience4j
#@+doc
# [source,yaml]
# ----
#@@c
#@@language yaml
# 动态配置测试 - 断路器故障率阈值
resilience4j:
  circuitbreaker:
    configs:
      default:
        # failure-rate-threshold: 50
        failure-rate-threshold: 75  # 改数字为了测试
#@+doc
# ----
#@-others
#@-leo
